controller_list:
  - name: fake_manipulator_controller
    joints: [ur5_arm_shoulder_pan_joint, ur5_arm_shoulder_lift_joint, ur5_arm_elbow_joint, ur5_arm_wrist_1_joint, ur5_arm_wrist_2_joint, ur5_arm_wrist_3_joint, ur5_arm_ee_fixed_joint, ur5_arm_camera_mount_joint, ur5_arm_camera_joint, ur5_arm_laser_pointer_joint, ur5_arm_camera_optical_joint]
